# Generated by Django 3.2.9 on 2021-11-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='creditor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='short_name',
            field=models.CharField(max_length=30),
        ),
    ]
