# Generated by Django 3.2.9 on 2021-11-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_user', '0002_auto_20211128_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdocument',
            name='id',
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='document_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
