# Generated by Django 3.2.9 on 2021-11-28 05:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('priority', models.TextField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium')),
                ('status', models.TextField(choices=[('open', 'Open'), ('inprogress', 'Inprogress'), ('closed', 'Closed')], default='open')),
                ('debiter', models.CharField(max_length=40)),
                ('total_amount', models.BigIntegerField()),
                ('recovered', models.BigIntegerField(default=0)),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('entry_id', models.IntegerField(primary_key=True, serialize=False)),
                ('entry_type', models.TextField(choices=[('conversation', 'Conversation'), ('legal', 'Legal'), ('transaction', 'Transaction')], default='conversation')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('amount_recovered', models.BigIntegerField(null=True)),
                ('subject', models.CharField(max_length=2000)),
                ('case', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='case_management.case', verbose_name='case_id')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('case', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='case_management.case', verbose_name='case_id')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=20)),
                ('doc_type', models.TextField(choices=[('client', 'Client'), ('internal', 'Internal')], default='client')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('case', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='case_management.case', verbose_name='case_id')),
            ],
        ),
    ]
