# Generated by Django 3.2.9 on 2021-11-28 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_user', '0001_initial'),
        ('case_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='assignee_id'),
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='case_user.client', verbose_name='client_id'),
        ),
    ]
