# Generated by Django 3.2.9 on 2021-11-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debitor',
            fields=[
                ('debitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='username',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
