# Generated by Django 3.2.9 on 2021-11-28 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_auto_20211128_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='convo_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='legal_case_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='entry_type',
            field=models.TextField(choices=[('general', 'Conversation'), ('legal', 'Legal'), ('transaction', 'Transaction')], default='general'),
        ),
    ]
